ES-75: Enhance Git hooks to prevent direct commits and pushes to master and develop branches, enforcing the use of feature branches and Pull Requests.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,8 @@
+current_branch=$(git rev-parse --abbrev-ref HEAD)
+
+if [ "$current_branch" = "master" ] || [ "$current_branch" = "develop" ]; then
+  echo "❌ Error: Direct commits to '$current_branch' are not allowed. Please use a feature branch and create a Pull Request."
+  exit 1
+fi
+
 npx lint-staged
